[package]
name = "blink-rp2040"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.0"
cortex-m = "0.7.0"
rp2040-boot2 = '0.3.0'
rp2040-pac = { git = "https://github.com/rp-rs/rp2040-pac", branch = "main" }
panic-halt = "0.2.0"
rp2040-hal = '0.8.2'
embedded-hal = '0.2.5'
